services:
  - type: web
    name: biblio-territorial-server
    runtime: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=256
